import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import { isAppEnabled, createStorageAdapter, getSettings, applyVaultPersona, cacheAiPersona } from '@/profiles'
// Generated by Copilot
import type { Profile, QuickLink } from '@/shared/types'

export default function Home() {
  const router = useRouter()
  const [profile, setProfile] = useState<Profile | null>(null)
  const [isConfigured, setIsConfigured] = useState(false)
  const [quickLinks, setQuickLinks] = useState<QuickLink[]>([])
  const [avatarSrc, setAvatarSrc] = useState<string>('')
  const aiConfigured = Boolean(profile?.ai_persona?.apiKey?.trim())

  useEffect(() => {
    const p = getSettings()
    setProfile(p)
    setIsConfigured(!!p.gh_pat && !!p.github_repo)

    // vault からクイックリンクと AI人格を取得（vault が primary source）
    if (p.gh_pat && p.github_repo) {
      const adapter = createStorageAdapter()

      // クイックリンク
      adapter
        .getPortalConfig()
        .then((config) => {
          if (config.links?.length) {
            setQuickLinks(
              [...config.links].sort((a, b) => (a.sortOrder ?? 0) - (b.sortOrder ?? 0))
            )
          }
        })
        .catch(() => {})

      // AI人格（vault/persona/persona.md を primary source として適用）
      adapter
        .getAiPersona()
        .then(async (persona) => {
          if (persona) {
            cacheAiPersona(p, persona)
            setProfile((prev) => prev ? applyVaultPersona(prev, persona) : prev)
            // raw.githubusercontent.com はプライベートリポジトリにPAT認証が必要なためプロキシfetch
            if (persona.avatarUrl?.startsWith('https://raw.githubusercontent.com/')) {
              try {
                const res = await fetch(persona.avatarUrl, {
                  headers: { Authorization: `Bearer ${p.gh_pat}` },
                })
                if (res.ok) {
                  const blob = await res.blob()
                  setAvatarSrc(URL.createObjectURL(blob))
                }
              } catch {
                // フォールバック: avatarUrl をそのまま使用
              }
            } else if (persona.avatarUrl) {
              setAvatarSrc(persona.avatarUrl)
            }
          }
        })
        .catch(() => {})
    }
  }, [])

  if (!profile) return null

  const persona = profile.ai_persona
  const diaryDescription = isAppEnabled('chat') && aiConfigured
    ? '今日の記録を書く（保存後にAI振り返り）'
    : '今日の記録を書く'
  const chatDescription = aiConfigured ? 'AIに相談・整理する' : 'AI設定を行う'

  return (
    <div className="min-h-screen bg-zinc-950 text-zinc-100 font-sans">
      {/* Header */}
      <header className="border-b border-zinc-800 px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-3">
          {avatarSrc ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              src={avatarSrc}
              alt={persona?.name}
              className="w-8 h-8 rounded-full object-cover"
            />
          ) : (
            <span className="text-xl">{profile.emoji}</span>
          )}
          <h1 className="text-lg font-semibold tracking-tight">Portal</h1>
        </div>

        <div className="flex items-center gap-2">
          {/* プロファイル表示のみ（ADR-005: 切り替えはUI非対応、設定画面経由） */}
          <span className="flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-medium bg-zinc-800 text-zinc-400">
            {profile.emoji} {profile.label}
          </span>

          {/* 設定ボタン */}
          <button
            onClick={() => router.push('/settings')}
            className="rounded-full p-2 text-zinc-400 hover:text-zinc-100 hover:bg-zinc-800 transition-colors"
            title="設定"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="18"
              height="18"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <circle cx="12" cy="12" r="3" />
              <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z" />
            </svg>
          </button>
        </div>
      </header>

      <main className="max-w-2xl mx-auto px-6 py-10">
        {/* 未設定の場合の警告 */}
        {!isConfigured && (
          <div
            className="mb-8 rounded-xl border border-amber-500/30 bg-amber-500/10 p-5 cursor-pointer"
            onClick={() => router.push('/settings')}
          >
            <p className="text-sm text-amber-400 font-medium">
              GitHub PAT とリポジトリを設定してください
            </p>
            <p className="mt-1 text-xs text-zinc-400">
              クリックして設定画面へ → PAT・リポジトリを入力する
            </p>
          </div>
        )}

        {/* AI 人格 挨拶 (アバター設定時のみ表示・フェードインでフラッシング防止) */}
        {persona?.name && isConfigured && avatarSrc && (
          <div className="mb-8 flex items-center gap-3 fade-in-delayed">
            <img
              src={avatarSrc}
              alt={persona.name}
              className="w-10 h-10 rounded-full object-cover shrink-0 avatar-img"
              decoding="async"
              loading="eager"
            />
            <div>
              <p className="text-sm text-zinc-300">
                おはよう、{persona.userCallName}。今日も一緒に頑張ろう。
              </p>
              <p className="text-xs text-zinc-600 mt-0.5">— {persona.name}</p>
            </div>
          </div>
        )}

        {/* 機能カード */}
        <div className="grid grid-cols-2 gap-4 mb-8">
          <FeatureCard
            icon="📓"
            title="日記"
            description={diaryDescription}
            onClick={() => router.push('/diary')}
          />
          {isAppEnabled('chat') && (
            <FeatureCard
              icon="💬"
              title="AIチャット"
              description={chatDescription}
              onClick={() => router.push(aiConfigured ? '/chat' : '/settings')}
            />
          )}
          <FeatureCard
            icon="✅"
            title="チェックリスト"
            description="今日のタスクを確認"
            onClick={() => router.push('/checklist')}
          />
          {isAppEnabled('backlog') && (
            <FeatureCard
              icon="📋"
              title="Backlog"
              description="担当課題を確認"
              onClick={() => router.push('/backlog')}
            />
          )}
          {isAppEnabled('github-issues') && (
            <FeatureCard
              icon="🐙"
              title="GitHub Issues"
              description="担当 Issue を確認"
              onClick={() => router.push('/issues')}
            />
          )}
          {isAppEnabled('finance') && (
            <FeatureCard
              icon="💰"
              title="家計管理"
              description="収支を記録"
              onClick={() => router.push('/finance')}
            />
          )}
        </div>

        {/* クイックリンク */}
        {isAppEnabled('quicklinks') && quickLinks.length > 0 && (
          <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-5">
            <h2 className="text-xs font-semibold uppercase tracking-widest text-zinc-500 mb-4">
              クイックリンク
            </h2>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
              {quickLinks.map((link) => (
                <a
                  key={link.id}
                  href={link.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="flex items-center gap-2 rounded-lg px-3 py-2 text-sm text-zinc-300 hover:text-zinc-100 hover:bg-zinc-800 transition-colors"
                >
                  <span className="text-base shrink-0">{link.emoji}</span>
                  <span className="truncate">{link.name}</span>
                </a>
              ))}
            </div>
          </div>
        )}
      </main>
    </div>
  )
}

function FeatureCard({
  icon,
  title,
  description,
  onClick,
}: {
  icon: string
  title: string
  description: string
  onClick: () => void
}) {
  return (
    <button
      onClick={onClick}
      className="rounded-xl border border-zinc-800 bg-zinc-900 p-5 hover:border-zinc-600 hover:bg-zinc-800 transition-all text-left w-full"
    >
      <span className="text-2xl">{icon}</span>
      <h3 className="mt-3 text-sm font-semibold">{title}</h3>
      <p className="mt-1 text-xs text-zinc-400">{description}</p>
    </button>
  )
}
